### ISSUE TITLE
webgui and ssh inaccessible after some time even that music is still playing (via Tidal Connect and squeezelite)

### ISSUE THREAD

**Issue by godzinilla** [TonyTromp/tidal-connect-docker#43]
Hello,

My setup is:
RPi 3B+
Hifiberry DAC2HD
Hifiberry DSP add-on
cheap 16 GB sdcard

Freshly installed and configured. I am only using this as endpoint for my squeezelite (just the ip address of my server is added). I was able to install and configure tidal-connect-docker and able to play the music, but after some time I am loosing the access to the webgui and even to the ssh.

For the webgui there is
`ERR_CONNECTION_REFUSED`
(I am using Chrome).

For the ssh:
```
# ls
-bash: /bin/ls: Input/output error
```
(Solar-PuTTY)

Despite that I still able to use Tidal Connect and squeezelite and play music without interruptions.

```
# cat CONFIG
FRIENDLY_NAME=hifiberry-x-yamaha
MODEL_NAME=hifiberry-x-yamaha
MQA_PASSTHROUGH=false
MQA_CODEC=false
PLAYBACK_DEVICE=snd_rpi_hifiberry_dacplushd: HiFiBerry DAC+ HD HiFi pcm179x-hifi-0 (hw:0,0)
#
```
```
# more docker-compose.yml
version: '2.2'
services:
  tidal-connect:
    container_name: tidal_connect
    env_file:
      - .env
    image: edgecrush3r/tidal-connect:latest
    tty: true
    network_mode: host
    devices:
     - /dev/snd
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - /var/run/dbus:/var/run/dbus
    restart: always
    dns:
      - 8.8.8.8
#
```

```
# more entrypoint.sh
#!/bin/bash

echo "Starting Speaker Application in Background (TMUX)"
/usr/bin/tmux new-session -d -s speaker_controller_application '/app/ifi-tidal-release/bin/speaker_controller_application'

echo "Starting TIDAL Connect.."
/app/ifi-tidal-release/bin/tidal_connect_application \
   --tc-certificate-path "/app/ifi-tidal-release/id_certificate/IfiAudio_ZenStream.dat" \
   --playback-device "${PLAYBACK_DEVICE}" \
   -f "${FRIENDLY_NAME}" \
   --codec-mpegh true \
   --codec-mqa ${MQA_CODEC} \
   --model-name "${MODEL_NAME}" \
   --disable-app-security false \
   --disable-web-security false \
   --enable-mqa-passthrough ${MQA_PASSTHROUGH} \
   --log-level 3 \
   --enable-websocket-log "0" \

echo "TIDAL Connect Container Stopped.."
#
```
